services:
  witness-demo:
    image: weboftrust/keri-witness-demo:1.1.0
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5642/oobi"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    stop_grace_period: 0s
    # volumes:
    #   - ./config/witness-demo:/keripy/scripts/keri/cf/main
    # network_mode: "host"
    ports:
      - 5642:5642
      - 5643:5643
      - 5644:5644
