x-healthcheck: &x-healthcheck
  interval: 3s
  timeout: 3s
  retries: 20
  start_period: 2s

x-witness: &x-witness
  build:
    context: images/keripy-witness
    dockerfile: Dockerfile
  healthcheck:
    <<: *x-healthcheck
    test: ["CMD", "/healthcheck.sh"]
  stop_grace_period: 0s

configs:
  wan.json:
    content: |
      {
          "dt": "2025-01-01T00:00:00.000000+00:00",
          "wan": {
              "dt": "2025-01-01T00:00:00.000000+00:00",
              "curls": ["http://localhost:5642/"]
          }
      }
  wil.json:
    content: |
      {
          "dt": "2025-01-01T00:00:00.000000+00:00",
          "wil": {
              "dt": "2025-01-01T00:00:00.000000+00:00",
              "curls": ["http://localhost:5643/"]
          }
      }
  wes.json:
    content: |
      {
          "dt": "2025-01-01T00:00:00.000000+00:00",
          "wes": {
              "dt": "2025-01-01T00:00:00.000000+00:00",
              "curls": ["http://localhost:5644/"]
          }
      }

services:
  witness-1:
    <<: *x-witness
    env_file:
      - config/witness-1.env
    stop_grace_period: 0s
    environment:
      KERI_LOG_LEVEL: DEBUG
    ports:
      - 5641:5641

  witness-demo:
    image: weboftrust/keri:1.2.6
    healthcheck:
      <<: *x-healthcheck
      test: wget http://0.0.0.0:5642/oobi -q -O -
    command: witness demo
    configs:
      - source: wan.json
        target: /keripy/scripts/keri/cf/main/wan.json
      - source: wes.json
        target: /keripy/scripts/keri/cf/main/wes.json
      - source: wil.json
        target: /keripy/scripts/keri/cf/main/wil.json
    environment:
      KERI_LOG_LEVEL: DEBUG
      KERI_WITNESS_PORT: 5642
      PYTHONUNBUFFERED: 1
      PYTHONIOENCODING: UTF-8
    stop_grace_period: 0s
    ports:
      - 5642:5642
      - 5643:5643
      - 5644:5644
