x-healthcheck: &x-healthcheck
  test: ["CMD", "/healthcheck.sh"]
  interval: 3s
  timeout: 3s
  retries: 20
  start_period: 2s

x-witness: &x-witness
  build:
    context: images/keripy-witness
    dockerfile: Dockerfile
  healthcheck:
    <<: *x-healthcheck
  stop_grace_period: 0s

services:
  witness-1:
    <<: *x-witness
    env_file:
      - config/witness-1.env
    ports:
      - 5641:5641

  witness-2:
    <<: *x-witness
    env_file:
      - config/witness-2.env
    ports:
      - 5642:5642

  witness-3:
    <<: *x-witness
    env_file:
      - config/witness-3.env
    ports:
      - 5643:5643

  dynamodb:
    build:
      context: images/dynamodb
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    healthcheck:
      <<: *x-healthcheck
