#!/usr/bin/env python
from keri.core.coring import MtrDex, Matter, Sizage
from keri.core.indexing import IdrDex, Indexer, Xizage
from keri.core.counting import CtrDex_1_0, CtrDex_2_0, Counter, Cizage
from json import dumps


def format_size(sizes: Sizage | Xizage) -> str:
    result = dict()

    for key, size in sizes.items():
        if not key.startswith("__"):
            result[key] = {
                "hs": size.hs,
                "ss": size.ss,
                "os": size.os if hasattr(size, "os") else 0,
                "fs": size.fs or 0,
                "ls": size.ls if hasattr(size, "ls") and size.ls else 0,
                "xs": size.xs if hasattr(size, "xs") and size.xs else 0,
            }

    return dumps(result)


def format_codes(names: dict[str, str]) -> str:
    result = dict()

    for name, code in names.items():
        if (
            not code.startswith("-")
            and not code.startswith("__")
            and not name.startswith("TBD")
        ):
            result[name] = code

        if (
            code.startswith("-")
            and not code.startswith("--")
            and not code.startswith("-_")
        ):
            result[name] = code.lstrip("-")

    return dumps(result)


print("// THIS FILE IS AUTO-GENERATED")
print("// DO NOT EDIT THIS FILE DIRECTLY")
print("// Use scripts/generate-codec.py to generate this file")

print(f"export const MatterTableInit = {format_size(Matter.Sizes)}")
print(f"export const MatterCode = {format_codes(MtrDex.__dict__)}")
print(f"export const IndexTableInit = {format_size(Indexer.Sizes)}")
print(f"export const IndexCode = {format_codes(IdrDex.__dict__)}")
print(f"export const CountCode_10 = {format_codes(CtrDex_1_0.__dict__)}")
print(f"export const CountCode_20 = {format_codes(CtrDex_2_0.__dict__)}")
